# Uncomment and fill any platforms you use.
# github: IndieMarz
# patreon: # your-patreon-username
# open_collective: # your-oc-name
# ko_fi: # your-kofi-username
# custom: ["https://www.patreon.com/posts/newsletter-1-has-157306464"]
